# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: maxon
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.1
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint3
    - joint4
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /maxon/canopen_motor/joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint3
      - joint4